
name: Terraform Workflow

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3

      # Set up AWS credentials
      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Install the latest version of Terraform CLI
      - name: Install Terraform
        run: |
          wget https://releases.hashicorp.com/terraform/0.15.0/terraform_0.15.0_linux_amd64.zip
          unzip terraform_0.15.0_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          terraform --version

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: terraform init

      # Checks that all Terraform configuration files adhere to a canonical format
      # - name: Terraform Format
      #   run: terraform fmt -check

      # Generates an execution plan for Terraform..

      # - name: Terraform Plan
      #   run: terraform plan -input=false # -out tfplan
      
      - name: Apply Terraform
        run: terraform apply -auto-approve
        
        
      - name: Download keys as artifacts
        run: |
          mkdir -p keys
          mv terraform-generated-keys/* keys/ # adjust the path as per your generated keys
        if: always()
        
      - name: Upload keys as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: terraform-keys
          path: keys/
      
