# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: tfsec

on:
  push:
    branches: [ "stage" ]
  pull_request:
    branches: [ "stage" ]
  schedule:
    - cron: '34 21 * * 4'

jobs:
  tfsec:
    name: Run tfsec sarif report
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: git clone https://github.com/smanikkalai/WevServer.git
        uses: actions/checkout@v3

      - name: Run tfsec
        uses: aquasecurity/tfsec-sarif-action@21ded20e8ca120cd9d3d6ab04ef746477542a608
        with:
          sarif_file: tfsec.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: tfsec.sarif
      - name: Checkout
      uses: actions/checkout@v3

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
      run: terraform init
    
    
      - name: Terraform validate
      run: terraform validate
    
      - name: Terraform Plan
      run:  terraform plan -tfplan
      if: tfplan == 'tfplan'
        - terraform plan -input=false 
      - name: Terraform Apply
      if: github.ref == 'refs/heads/"stage"' && github.event_name == 'push'
      run: terraform apply -auto-approve -input=false    
